baseURL = "https://social.charlescisco.org/"
title = "Charles Cisco"
theme = "mkdir"
disableKinds = []

[languages]
  [languages.en]
    locale = "en-us"
    weight = 1

[pagination]
  pagerSize = 20

[params]
description = "Notes on reading, theology, and the humanities."

  [params.author]
  name = "Charles Cisco"
  username = "charlescisco"
  avatar = ""

[taxonomies]
category = "categories"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
